### ISSUE TITLE
 docs/includes/wunderground-key.md refers to inexting URL

### ISSUE THREAD

**Issue by titimoby** [ThingPulse/docs#1]
It looks like the procedure to get a Wunderground api key has changed.

**Comment by titimoby** [comment]
I think everything is now on:
https://www.wunderground.com/weather/api/d/pricing.html

**Comment by marcelstoer** [comment]
We've actually got rewriting in place for this in https://github.com/ThingPulse/docs/blob/master/.htaccess. Need to figure out why it doesn't work anymore.

Thanks for reporting.

**Comment by titimoby** [comment]
It was not that hard to figure out how to get the API key by myself, but you have such a nice package and doc that I feel it needs an issue ;)

Feel free to close it whenever you want.

**Comment by marcelstoer** [comment]
The file isn't deployed anymore as only the MkDocs site directory gets `rsync`ed: https://github.com/ThingPulse/docs/blob/master/.travis.yml#L16

I'll fix the build-deployment process later. For now I copied the file manually.
